object frmMimicPanel: TfrmMimicPanel
  Left = 329
  Top = 283
  BorderStyle = bsNone
  Caption = 'Mimic Panel'
  ClientHeight = 761
  ClientWidth = 1105
  Color = clBlack
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  WindowState = wsMaximized
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object scrlbxMimic: TScrollBox
    Left = 0
    Top = 3
    Width = 1105
    Height = 755
    Align = alClient
    AutoScroll = False
    BorderStyle = bsNone
    Color = clBlack
    ParentColor = False
    TabOrder = 0
    ExplicitWidth = 735
    ExplicitHeight = 794
  end
  object pnlHideShowBarTop: TPanel
    Left = 0
    Top = 0
    Width = 1105
    Height = 3
    Align = alTop
    BevelEdges = []
    BevelOuter = bvNone
    Color = clBlack
    ParentBackground = False
    TabOrder = 1
    OnClick = pnlHideShowBarTopClick
    ExplicitWidth = 735
  end
  object pnlHideShowBtm: TPanel
    Left = 0
    Top = 758
    Width = 1105
    Height = 3
    Align = alBottom
    BevelEdges = []
    BevelOuter = bvNone
    Color = clBlack
    ParentBackground = False
    TabOrder = 2
    OnClick = pnlHideShowBarTopClick
    ExplicitTop = 797
    ExplicitWidth = 735
  end
end
