program instructor;

uses
  Forms,
  uScenLoader in 'panels\uScenLoader.pas' {frmScenarioLoader},
  uScenBuilder in 'panels\uScenBuilder.pas' {frmScenBuilder},
  uERManager in '..\ersimulator\uERManager.pas',
  uERNetwork in '..\ersimulator\uERNetwork.pas',
  uERSystem in '..\ersimulator\uERSystem.pas',
  uSteppers in '..\framework\LibBaseUtils\Counter\uSteppers.pas',
  uThreadTimer in '..\framework\LibBaseUtils\Counter\uThreadTimer.pas',
  uVirtualTime in '..\framework\LibBaseUtils\Counter\uVirtualTime.pas',
  uEngineRoom in '..\engines\uEngineRoom.pas',
  uAuxSystem in '..\engines\system\uAuxSystem.pas',
  uBallastSystem in '..\engines\system\uBallastSystem.pas',
  uCommonSystem in '..\engines\system\uCommonSystem.pas',
  uFireFightingSystem in '..\engines\system\uFireFightingSystem.pas',
  uFuelOilSystem in '..\engines\system\uFuelOilSystem.pas',
  uNavComSystem in '..\engines\system\uNavComSystem.pas',
  uPMSSystem in '..\engines\system\uPMSSystem.pas',
  uPropulsionSystem in '..\engines\system\uPropulsionSystem.pas',
  uSeaFWSystem in '..\engines\system\uSeaFWSystem.pas',
  uConsumption in '..\engines\entity\uConsumption.pas',
  uEntity in '..\engines\entity\uEntity.pas',
  uGenerator in '..\engines\entity\uGenerator.pas',
  uPump in '..\engines\entity\uPump.pas',
  uTank in '..\engines\entity\uTank.pas',
  uFunction in '..\common\uFunction.pas',
  uListener in '..\common\uListener.pas',
  uDatabase in '..\common\uDatabase.pas',
  uDataType in '..\common\uDataType.pas',
  uDataBuffer in '..\network\uDataBuffer.pas',
  uNetBaseSocket in '..\network\uNetBaseSocket.pas',
  uNetworkManager in '..\network\uNetworkManager.pas',
  uPacketRegister in '..\network\uPacketRegister.pas',
  uTCPClient in '..\network\uTCPClient.pas',
  uTCPDatatype in '..\network\uTCPDatatype.pas',
  uTCPServer in '..\network\uTCPServer.pas',
  uSetting in '..\common\uSetting.pas',
  uStarter in 'uStarter.pas',
  uBallastSystemPanel in '..\ersimulator\panel\uBallastSystemPanel.pas' {frmBallastSystemPanel},
  uERPanel in 'panels\uERPanel.pas' {frmERPanel},
  uVerticalBar in '..\components\uVerticalBar.pas',
  uAnalogSensor in '..\components\uAnalogSensor.pas',
  uBaseComponent in '..\components\uBaseComponent.pas',
  uChart in '..\components\uChart.pas',
  uCircuitBreakerElement in '..\components\uCircuitBreakerElement.pas',
  uControlElement in '..\components\uControlElement.pas',
  uHorizontalBar in '..\components\uHorizontalBar.pas',
  uIPMS_Data in '..\components\uIPMS_Data.pas',
  uMotorControlDoubleSpeed in '..\components\uMotorControlDoubleSpeed.pas',
  uMotorControlElement in '..\components\uMotorControlElement.pas',
  uMotorControlStandby in '..\components\uMotorControlStandby.pas',
  uRunningHour in '..\components\uRunningHour.pas',
  uSetpoint in '..\components\uSetpoint.pas',
  uShortcut in '..\components\uShortcut.pas',
  uSwitchElement in '..\components\uSwitchElement.pas',
  uSwitchEvent in '..\components\uSwitchEvent.pas',
  uSwitchNBCD in '..\components\uSwitchNBCD.pas',
  uSwitchTriangle in '..\components\uSwitchTriangle.pas',
  uTankSensor in '..\components\uTankSensor.pas',
  uValveControl in '..\components\uValveControl.pas',
  uValveProportionally in '..\components\uValveProportionally.pas',
  ufrmLogger in '..\mimics\ufrmLogger.pas' {frmLogs},
  ufrmLogin in '..\mimics\ufrmLogin.pas' {frmLogin},
  ufrmMain in '..\mimics\ufrmMain.pas' {frmMainDisplay},
  uMimicsManager in '..\mimics\uMimicsManager.pas',
  uMimicsNetwork in '..\mimics\uMimicsNetwork.pas',
  uMimicsSystem in '..\mimics\uMimicsSystem.pas',
  ufrm24vDCPowerDistribution in '..\mimics\mimic\ufrm24vDCPowerDistribution.pas' {frm24vDCPowerDistribution},
  ufrm230v115vPowerDistribution in '..\mimics\mimic\ufrm230v115vPowerDistribution.pas' {frm230v115vPowerDistribution},
  ufrmAlarmHistory in '..\mimics\mimic\ufrmAlarmHistory.pas' {frmAlarmHistory},
  ufrmAlarmPresentation in '..\mimics\mimic\ufrmAlarmPresentation.pas' {frmAlarmPresentation},
  ufrmAlarmSummary in '..\mimics\mimic\ufrmAlarmSummary.pas' {frmAlarmSummary},
  ufrmAuxiliarySystemOverview in '..\mimics\mimic\ufrmAuxiliarySystemOverview.pas' {frmAuxiliarySystemOverview},
  ufrmBallastSystem in '..\mimics\mimic\ufrmBallastSystem.pas' {frmBallastSystem},
  ufrmBilgeSystem in '..\mimics\mimic\ufrmBilgeSystem.pas' {frmBilgeSystem},
  ufrmCAP in '..\mimics\mimic\ufrmCAP.pas' {frmCAP},
  ufrmCommandHistory in '..\mimics\mimic\ufrmCommandHistory.pas' {frmCommandHistory},
  ufrmCPP in '..\mimics\mimic\ufrmCPP.pas' {frmCPP},
  ufrmEmptyPage in '..\mimics\mimic\ufrmEmptyPage.pas' {frmEmptyPage},
  ufrmFireDetectionDeckTop in '..\mimics\mimic\ufrmFireDetectionDeckTop.pas' {frmFireDetectionDeckTop},
  ufrmFireDetectionDeckBottom in '..\mimics\mimic\ufrmFireDetectionDeckBottom.pas' {frmFireDetectionDeckBottom},
  ufrmFireFightingSystem in '..\mimics\mimic\ufrmFireFightingSystem.pas' {frmFireFightingSystem},
  ufrmFuelOilSystem in '..\mimics\mimic\ufrmFuelOilSystem.pas' {frmFuelOilSystem},
  ufrmFunctionAllocation in '..\mimics\mimic\ufrmFunctionAllocation.pas' {frmFuncAllocation},
  ufrmListOfDisabledElement in '..\mimics\mimic\ufrmListOfDisabledElement.pas' {frmListOfDisabledElement},
  ufrmListOfParameterChanges in '..\mimics\mimic\ufrmListOfParameterChanges.pas' {frmListOfParameterChanges},
  ufrmMachinerySpaceVentSystem in '..\mimics\mimic\ufrmMachinerySpaceVentSystem.pas' {frmMachinerySpaceVentSystem},
  ufrmMEPS in '..\mimics\mimic\ufrmMEPS.pas' {frmMEPS},
  ufrmMEPS_Exhaust in '..\mimics\mimic\ufrmMEPS_Exhaust.pas' {frmMEPS_Exhaust},
  ufrmMESB in '..\mimics\mimic\ufrmMESB.pas' {frmMESB},
  ufrmMESB_Exhaust in '..\mimics\mimic\ufrmMESB_Exhaust.pas' {frmMESB_Exhaust},
  ufrmMimics in '..\mimics\mimic\ufrmMimics.pas' {frmMimics},
  ufrmNavComSystem in '..\mimics\mimic\ufrmNavComSystem.pas' {frmNavComs},
  ufrmNetArchitect in '..\mimics\mimic\ufrmNetArchitect.pas' {frmNetArchitect},
  ufrmPowerManagementOverview in '..\mimics\mimic\ufrmPowerManagementOverview.pas' {frmPowerManagementOverview},
  ufrmPropultionConditions in '..\mimics\mimic\ufrmPropultionConditions.pas' {frmPropultionConditions},
  ufrmPropultionSystemOverview in '..\mimics\mimic\ufrmPropultionSystemOverview.pas' {frmPropultionSystemOverview},
  ufrmRunningHours in '..\mimics\mimic\ufrmRunningHours.pas' {frmRunningHours},
  ufrmSeaAndFreshWaterSystem in '..\mimics\mimic\ufrmSeaAndFreshWaterSystem.pas' {frmSeaAndFreshWaterSystem},
  ufrmTankOverview in '..\mimics\mimic\ufrmTankOverview.pas' {frmTankOverview},
  ufrmTOC in '..\mimics\mimic\ufrmTOC.pas' {frmTOC},
  ufrmUninterruptiblePS in '..\mimics\mimic\ufrmUninterruptiblePS.pas' {frmUninterruptiblePS},
  ufrmMimicKey in '..\mimics\mimic\ufrmMimicKey.pas' {frmMimicKey},
  ufrmAlarmConfiguration in '..\mimics\popmenu\ufrmAlarmConfiguration.pas' {frmAlarmConfiguration},
  ufrmAlarmString in '..\mimics\popmenu\ufrmAlarmString.pas' {frmSelectAlarmString},
  ufrmAlarmStringIndex in '..\mimics\popmenu\ufrmAlarmStringIndex.pas' {Form4},
  ufrmAttributeSet in '..\mimics\popmenu\ufrmAttributeSet.pas' {frmNewAttribute},
  ufrmConfDateTime in '..\mimics\popmenu\ufrmConfDateTime.pas' {frmConfDateTime},
  ufrmEdtAttribute in '..\mimics\popmenu\ufrmEdtAttribute.pas' {frmEdtAttribute},
  ufrmEdtEnumeration in '..\mimics\popmenu\ufrmEdtEnumeration.pas' {frmEdtEnumeration},
  ufrmEdtExpression in '..\mimics\popmenu\ufrmEdtExpression.pas' {frmEditExpression},
  ufrmEdtFilter in '..\mimics\popmenu\ufrmEdtFilter.pas' {frmEdtFilter},
  ufrmEdtMeasure in '..\mimics\popmenu\ufrmEdtMeasure.pas' {frmEdtMeasure},
  ufrmHelp in '..\mimics\popmenu\ufrmHelp.pas' {frmHelp},
  ufrmHistoricalRealtime in '..\mimics\popmenu\ufrmHistoricalRealtime.pas' {frmHistoricalRealtime},
  ufrmLineDisplay in '..\mimics\popmenu\ufrmLineDisplay.pas' {frmLineDisplay},
  ufrmLineMap in '..\mimics\popmenu\ufrmLineMap.pas' {frmLineMap},
  ufrmNewAttribute in '..\mimics\popmenu\ufrmNewAttribute.pas' {Form3},
  ufrmNewEnumeration in '..\mimics\popmenu\ufrmNewEnumeration.pas' {frmNewEnumeration},
  ufrmNewMeasure in '..\mimics\popmenu\ufrmNewMeasure.pas' {frmNewMeasure},
  ufrmNewPoint in '..\mimics\popmenu\ufrmNewPoint.pas' {Form1},
  ufrmNewResource in '..\mimics\popmenu\ufrmNewResource.pas' {frmNewResource},
  ufrmNewValue in '..\mimics\popmenu\ufrmNewValue.pas' {frmNewValue},
  ufrmODBCAdmin in '..\mimics\popmenu\ufrmODBCAdmin.pas' {frmODBCAdmin},
  ufrmPointPropts in '..\mimics\popmenu\ufrmPointPropts.pas' {frmPointPropts},
  ufrmPointView in '..\mimics\popmenu\ufrmPointView.pas' {frmPointView},
  ufrmProperties in '..\mimics\popmenu\ufrmProperties.pas' {frmProperts},
  ufrmPropertiesContainer in '..\mimics\popmenu\ufrmPropertiesContainer.pas' {frmContainer},
  ufrmPropertiesScreen in '..\mimics\popmenu\ufrmPropertiesScreen.pas' {frmScreen},
  ufrmSelectAlarmClass in '..\mimics\popmenu\ufrmSelectAlarmClass.pas' {frmSelectAlarmClass},
  ufrmSelectDevice in '..\mimics\popmenu\ufrmSelectDevice.pas' {frmSelectDevice},
  ufrmSelectEnumeration in '..\mimics\popmenu\ufrmSelectEnumeration.pas' {frmSelectEnumeration},
  ufrmSelectFieldView in '..\mimics\popmenu\ufrmSelectFieldView.pas' {frmSelectFieldView},
  ufrmSelectMeasure in '..\mimics\popmenu\ufrmSelectMeasure.pas' {frmSelectMeasure},
  ufrmSelectPoint in '..\mimics\popmenu\ufrmSelectPoint.pas' {Form2},
  ufrmSelectPointType in '..\mimics\popmenu\ufrmSelectPointType.pas' {frmPointType},
  ufrmSelectResource in '..\mimics\popmenu\ufrmSelectResource.pas' {frmSelectResource},
  ufrmSelectSort in '..\mimics\popmenu\ufrmSelectSort.pas' {frmSelectSort},
  ufrmSelectValue in '..\mimics\popmenu\ufrmSelectValue.pas' {frmSelectValue},
  ufrmValuePropts in '..\mimics\popmenu\ufrmValuePropts.pas' {frmValuePropts},
  uMimicPanel in 'panels\uMimicPanel.pas' {frmMimicPanel},
  uControllerManager in '..\server\uControllerManager.pas',
  uControllerNetwork in '..\server\uControllerNetwork.pas',
  uControllerSystem in '..\server\uControllerSystem.pas',
  uVCPTestForm in '..\server\tester\uVCPTestForm.pas' {frmVCPTest},
  uAAETestForm in '..\server\tester\uAAETestForm.pas' {frmAAETest},
  uCBATestForm in '..\server\tester\uCBATestForm.pas' {frmCBATest},
  uCBETestForm in '..\server\tester\uCBETestForm.pas' {frmCBETest},
  uCTRTestForm in '..\server\tester\uCTRTestForm.pas' {frmCTRTest},
  uDAETestForm in '..\server\tester\uDAETestForm.pas' {frmDAETest},
  uElementTesterForm in '..\server\tester\uElementTesterForm.pas' {frmTester},
  uElementTestForm in '..\server\tester\uElementTestForm.pas' {frmElementTest},
  uMCDTestForm in '..\server\tester\uMCDTestForm.pas' {frmMCDTest},
  uMCETestForm in '..\server\tester\uMCETestForm.pas' {frmMCETest},
  uMCSTestForm in '..\server\tester\uMCSTestForm.pas' {frmMCSTest},
  uRHEtestForm in '..\server\tester\uRHEtestForm.pas' {frmRHETest},
  uSAETestForm in '..\server\tester\uSAETestForm.pas' {frmSAETest},
  uSEETestForm in '..\server\tester\uSEETestForm.pas' {frmSEETest},
  uSPETestForm in '..\server\tester\uSPETestForm.pas' {frmSPETest},
  uSS1TestForm in '..\server\tester\uSS1TestForm.pas' {frmSS1Test},
  uSS2TestForm in '..\server\tester\uSS2TestForm.pas' {frmSS2Test},
  uSSETestForm in '..\server\tester\uSSETestForm.pas' {frmSSETest},
  uSSLTestForm in '..\server\tester\uSSLTestForm.pas' {frmSSLTest},
  uSWBTestForm in '..\server\tester\uSWBTestForm.pas' {frmSWBTest},
  uSWETestForm in '..\server\tester\uSWETestForm.pas' {frmSWETest},
  uSWNTestForm in '..\server\tester\uSWNTestForm.pas' {frmSWNTest},
  uVCETestForm in '..\server\tester\uVCETestForm.pas' {frmVCETest},
  uVCHTestform in '..\server\tester\uVCHTestform.pas' {frmVCHTest},
  uSPE in '..\elements\uSPE.pas',
  uSS1 in '..\elements\uSS1.pas',
  uSS2 in '..\elements\uSS2.pas',
  uSSE in '..\elements\uSSE.pas',
  uSSL in '..\elements\uSSL.pas',
  uSWB in '..\elements\uSWB.pas',
  uSWE in '..\elements\uSWE.pas',
  uSWN in '..\elements\uSWN.pas',
  uVCE in '..\elements\uVCE.pas',
  uVCH in '..\elements\uVCH.pas',
  uVCP in '..\elements\uVCP.pas',
  uAAE in '..\elements\uAAE.pas',
  uCBA in '..\elements\uCBA.pas',
  uCBE in '..\elements\uCBE.pas',
  uCTR in '..\elements\uCTR.pas',
  uDAE in '..\elements\uDAE.pas',
  uElement in '..\elements\uElement.pas',
  uElementController in '..\elements\uElementController.pas',
  uMCD in '..\elements\uMCD.pas',
  uMCE in '..\elements\uMCE.pas',
  uMCS in '..\elements\uMCS.pas',
  uRHE in '..\elements\uRHE.pas',
  uSAE in '..\elements\uSAE.pas',
  uSEE in '..\elements\uSEE.pas',
  uPCSPanel in 'panels\uPCSPanel.pas' {frmPCSPanel},
  uPCSSystem in '..\PCS\uPCSSystem.pas',
  uPCSNetwork in '..\PCS\uPCSNetwork.pas',
  uPMSSystemPanel in '..\ersimulator\panel\uPMSSystemPanel.pas' {frmPMSSystemPanel},
  ufrmAuthorization in '..\mimics\popmenu\ufrmAuthorization.pas' {frmAuthorization},
  uAvailableTimes in 'panels\uAvailableTimes.pas' {frmAvailTimes},
  uSwitchboard in '..\engines\entity\uSwitchboard.pas',
  uScenario in '..\common\uScenario.pas',
  uComputer in '..\components\uComputer.pas',
  uPMSDataElement in '..\common\uPMSDataElement.pas',
  uDBSupportClasses in '..\common\uDBSupportClasses.pas',
  uAvailableScenario in 'panels\uAvailableScenario.pas' {frmAvailScenario},
  uCPP in '..\engines\entity\uCPP.pas',
  uGearBox in '..\engines\entity\uGearBox.pas',
  uMainEngine in '..\engines\entity\uMainEngine.pas',
  uPMSEditor in 'panels\uPMSEditor.pas' {frmPMSEditor},
  uAvailablePMSCondition in 'panels\uAvailablePMSCondition.pas' {frmAvailPMSCondition},
  uInstructorPanel in 'uInstructorPanel.pas' {frmInstructorPanel},
  uInstructorSystem in 'uInstructorSystem.pas',
  uNetArchitectur in 'panels\uNetArchitectur.pas' {frmNetPanel},
  uPCSPanelBridge in '..\PCS\uPCSPanelBridge.pas' {frmPCSPanelBridge},
  uDataLogger in 'panels\uDataLogger.pas' {frmLogger},
  uInstructorNetwork in 'uInstructorNetwork.pas',
  uNetworkStatus in 'panels\uNetworkStatus.pas' {frmNetStatus},
  uFreezeFrom in '..\common\uFreezeFrom.pas' {frmFreeze},
  uElementTables in '..\elements\uElementTables.pas',
  uPCSLocalControlPanel in '..\ersimulator\panel\uPCSLocalControlPanel.pas' {frmPCSLocalControlPanel},
  uPCSDataElement in '..\common\uPCSDataElement.pas',
  uAvailablePCSCondition in 'panels\uAvailablePCSCondition.pas' {frmAvailPCSCondition},
  uPCSEditor in 'panels\uPCSEditor.pas' {frmPCSEditor},
  uClientControl in 'panels\uClientControl.pas' {frmClientControl},
  uProgress in 'panels\uProgress.pas' {frmProgress},
  uAlarmRudder in 'panels\uAlarmRudder.pas' {frmAlarmRudder},
  uAlarmRudderClass in 'panels\uAlarmRudderClass.pas',
  uAvailableFACondition in 'panels\uAvailableFACondition.pas' {frmAvailFACondition},
  uFAEditor in 'panels\uFAEditor.pas' {frmFAEditor},
  uTelegram in 'panels\uTelegram.pas' {frmTelegram},
  uRudderIndicator in 'panels\uRudderIndicator.pas' {frmRudderIndicator},
  uFireFighting in 'panels\uFireFighting.pas' {frmFireFighting},
  uNav_CommSystem in 'panels\uNav_CommSystem.pas' {frmNav_CommSystem},
  uTankOverview in 'panels\uTankOverview.pas' {frmTanksOverview},
  uTankOverviewInput in 'panels\uTankOverviewInput.pas' {frmTankOverInput},
  uBilgeSystemIns in 'panels\uBilgeSystemIns.pas' {frmBilgeSystemIns},
  uSWEInput in 'panels\uSWEInput.pas' {frmSWEInput},
  uAuxSystemOverview in 'panels\uAuxSystemOverview.pas' {frmAuxSystemOverview},
  uTanksEditor in 'panels\uTanksEditor.pas' {frmTanksEditor},
  uAvailableTanksCondition in 'panels\uAvailableTanksCondition.pas' {frmTanksCondition},
  uPowerManagementSys in 'panels\uPowerManagementSys.pas' {frmPowerManagementSyst},
  uVentSystem in 'panels\uVentSystem.pas' {frmVentSystem},
  uAxisAttribute in '..\components\TrendChart\uAxisAttribute.pas',
  uGridAttribute in '..\components\TrendChart\uGridAttribute.pas',
  uLegendAttribute in '..\components\TrendChart\uLegendAttribute.pas',
  uLineAttribute in '..\components\TrendChart\uLineAttribute.pas',
  uTrendChart in '..\components\TrendChart\uTrendChart.pas',
  uTrendData in '..\components\TrendChart\uTrendData.pas',
  uTrendDataSeries in '..\components\TrendChart\uTrendDataSeries.pas',
  uTrendDataType in '..\components\TrendChart\uTrendDataType.pas',
  ufrmAxis in '..\datatrend\ufrmAxis.pas' {frmAxis},
  ufrmChart in '..\datatrend\ufrmChart.pas' {frmChartOption},
  ufrmDataTrend in '..\datatrend\ufrmDataTrend.pas' {frmTrending},
  ufrmExpression in '..\datatrend\ufrmExpression.pas' {frmExpression},
  ufrmGridOption in '..\datatrend\ufrmGridOption.pas' {frmGrid},
  ufrmLegend in '..\datatrend\ufrmLegend.pas' {frmLegend},
  ufrmLineAttribute in '..\datatrend\ufrmLineAttribute.pas' {frmLineAttribute},
  ufrmLinePoint in '..\datatrend\ufrmLinePoint.pas' {frmPointID},
  ufrmLines in '..\datatrend\ufrmLines.pas' {frmLines},
  ufrmLogged in '..\datatrend\ufrmLogged.pas' {frmLogged},
  ufrmLoggedExpression in '..\datatrend\ufrmLoggedExpression.pas' {frmLoggedExpression},
  ufrmNewAxis in '..\datatrend\ufrmNewAxis.pas' {frmNewAxis},
  ufrmSelectTrend in '..\datatrend\ufrmSelectTrend.pas' {frmSelectTrend},
  ufrmSetAxisProp in '..\datatrend\ufrmSetAxisProp.pas' {frmSetAxisProp},
  ufrmSetXAxisProp in '..\datatrend\ufrmSetXAxisProp.pas' {frmSetXAxisProp},
  ufrmSetYAxisProp in '..\datatrend\ufrmSetYAxisProp.pas' {frmSetYAxisProp},
  ufrmTableSelect in '..\datatrend\ufrmTableSelect.pas' {frmTableSelect},
  ufrmTrendControlPropts in '..\datatrend\ufrmTrendControlPropts.pas' {frmTrenControlPropts},
  ufrmSelectElement in '..\mimics\popmenu\ufrmSelectElement.pas' {frmSelectElement},
  uFireFightingControlSystem in 'panels\uFireFightingControlSystem.pas' {frmFFSystem},
  ufrmReport in '..\mimics\popmenu\ufrmReport.pas' {frmReport},
  ufrmSetpoint in '..\mimics\popmenu\ufrmSetpoint.pas' {frmSetpoint},
  uACSControl in 'panels\uACSControl.pas' {frmACSControl},
  uPropulsionConditionsSet in 'panels\uPropulsionConditionsSet.pas' {frmPropulsionConditions},
  uTankSystemPanel in 'panels\uTankSystemPanel.pas' {frmTankSystemPanel},
  ufrmAlarmSummaryDG in '..\mimics\mimic\ufrmAlarmSummaryDG.pas' {frmAlarmSummaryDG},
  ufrmAlarmSummaryDIST in '..\mimics\mimic\ufrmAlarmSummaryDIST.pas' {frmAlarmSummaryDIST},
  ufrmAlarmSummaryPROP in '..\mimics\mimic\ufrmAlarmSummaryPROP.pas' {frmAlarmSummaryPROP},
  ufrmAlarmSummaryAUX in '..\mimics\mimic\ufrmAlarmSummaryAUX.pas' {frmAlarmSummaryAUX},
  ufrmAlarmSummaryFUEL in '..\mimics\mimic\ufrmAlarmSummaryFUEL.pas' {frmAlarmSummaryFUEL},
  ufrmAlarmSummaryDMST in '..\mimics\mimic\ufrmAlarmSummaryDMST.pas' {frmAlarmSummaryDMST},
  ufrmAlarmSummaryHVAC in '..\mimics\mimic\ufrmAlarmSummaryHVAC.pas' {frmAlarmSummaryHVAC},
  ufrmAlarmSummaryFFDC in '..\mimics\mimic\ufrmAlarmSummaryFFDC.pas' {frmAlarmSummaryFFDC},
  ufrmAlarmSummaryNAV in '..\mimics\mimic\ufrmAlarmSummaryNAV.pas' {frmAlarmSummaryNAV},
  ufrmAlarmSummaryBALL in '..\mimics\mimic\ufrmAlarmSummaryBALL.pas' {frmAlarmSummaryBALL},
  ufrmAlarmSummaryIPMS in '..\mimics\mimic\ufrmAlarmSummaryIPMS.pas' {frmAlarmSummaryIPMS},
  lognya in '..\datatrend\lognya.pas' {Form5},
  uFuelOilPanel in 'panels\uFuelOilPanel.pas' {frmFuelOilPanel},
  uBallastPanel in 'panels\uBallastPanel.pas' {frmBallastPanel},
  uFreshWaterPanel in 'panels\uFreshWaterPanel.pas' {frmFreshWaterPanel};

{$R *.res}
{$R IPMS_Resource.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;

  BeginSimulation;
  Application.CreateForm(TfrmInstructorPanel, frmInstructorPanel);
  Application.CreateForm(TfrmLogin, frmLogin);
  Application.CreateForm(TfrmFFSystem, frmFFSystem);
  Application.CreateForm(TfrmReport, frmReport);
  Application.CreateForm(TfrmSetpoint, frmSetpoint);
  Application.CreateForm(TfrmACSControl, frmACSControl);
  Application.CreateForm(TfrmPropulsionConditions, frmPropulsionConditions);
  Application.CreateForm(TfrmTankSystemPanel, frmTankSystemPanel);
  Application.CreateForm(TForm5, Form5);
  Application.CreateForm(TfrmFuelOilPanel, frmFuelOilPanel);
  Application.CreateForm(TfrmBallastPanel, frmBallastPanel);
  Application.CreateForm(TfrmFreshWaterPanel, frmFreshWaterPanel);
  StartNetwork;

  Application.Run;

  EndSimulation;
end.
