program Mimics;



uses
  Forms,
  ufrmMain in 'ufrmMain.pas' {frmMainDisplay},
  ufrmLogin in 'ufrmLogin.pas' {frmLogin},
  ufrmMimics in 'mimic\ufrmMimics.pas' {frmMimics},
  ufrmMimicKey in 'mimic\ufrmMimicKey.pas' {frmMimicKey},
  ufrmEmptyPage in 'mimic\ufrmEmptyPage.pas' {frmEmptyPage},
  ufrmTOC in 'mimic\ufrmTOC.pas' {frmTOC},
  ufrmFunctionAllocation in 'mimic\ufrmFunctionAllocation.pas' {frmFuncAllocation},
  ufrmNavComSystem in 'mimic\ufrmNavComSystem.pas' {frmNavComs},
  ufrmNetArchitect in 'mimic\ufrmNetArchitect.pas' {frmNetArchitect},
  ufrmPowerManagementOverview in 'mimic\ufrmPowerManagementOverview.pas' {frmPowerManagementOverview},
  ufrm230v115vPowerDistribution in 'mimic\ufrm230v115vPowerDistribution.pas' {frm230v115vPowerDistribution},
  ufrm24vDCPowerDistribution in 'mimic\ufrm24vDCPowerDistribution.pas' {frm24vDCPowerDistribution},
  ufrmUninterruptiblePS in 'mimic\ufrmUninterruptiblePS.pas' {frmUninterruptiblePS},
  ufrmPropultionSystemOverview in 'mimic\ufrmPropultionSystemOverview.pas' {frmPropultionSystemOverview},
  ufrmCPP in 'mimic\ufrmCPP.pas' {frmCPP},
  ufrmMEPS in 'mimic\ufrmMEPS.pas' {frmMEPS},
  ufrmMESB in 'mimic\ufrmMESB.pas' {frmMESB},
  ufrmMEPS_Exhaust in 'mimic\ufrmMEPS_Exhaust.pas' {frmMEPS_Exhaust},
  ufrmMESB_Exhaust in 'mimic\ufrmMESB_Exhaust.pas' {frmMESB_Exhaust},
  ufrmPropultionConditions in 'mimic\ufrmPropultionConditions.pas' {frmPropultionConditions},
  ufrmFireDetectionDeckTop in 'mimic\ufrmFireDetectionDeckTop.pas' {frmFireDetectionDeckTop},
  ufrmFireDetectionDeckBottom in 'mimic\ufrmFireDetectionDeckBottom.pas' {frmFireDetectionDeckBottom},
  ufrmMachinerySpaceVentSystem in 'mimic\ufrmMachinerySpaceVentSystem.pas' {frmMachinerySpaceVentSystem},
  ufrmFireFightingSystem in 'mimic\ufrmFireFightingSystem.pas' {frmFireFightingSystem},
  ufrmBallastSystem in 'mimic\ufrmBallastSystem.pas' {frmBallastSystem},
  ufrmBilgeSystem in 'mimic\ufrmBilgeSystem.pas' {frmBilgeSystem},
  ufrmAuxiliarySystemOverview in 'mimic\ufrmAuxiliarySystemOverview.pas' {frmAuxiliarySystemOverview},
  ufrmTankOverview in 'mimic\ufrmTankOverview.pas' {frmTankOverview},
  ufrmSeaAndFreshWaterSystem in 'mimic\ufrmSeaAndFreshWaterSystem.pas' {frmSeaAndFreshWaterSystem},
  ufrmRunningHours in 'mimic\ufrmRunningHours.pas' {frmRunningHours},
  ufrmListOfDisabledElement in 'mimic\ufrmListOfDisabledElement.pas' {frmListOfDisabledElement},
  ufrmListOfParameterChanges in 'mimic\ufrmListOfParameterChanges.pas' {frmListOfParameterChanges},
  ufrmCommandHistory in 'mimic\ufrmCommandHistory.pas' {frmCommandHistory},
  uDataType in '..\common\uDataType.pas',
  uFunction in '..\common\uFunction.pas',
  uSetting in '..\common\uSetting.pas',
  uDatabase in '..\common\uDatabase.pas',
  uListener in '..\common\uListener.pas',
  uMimicsManager in 'uMimicsManager.pas',
  uNetworkManager in '..\network\uNetworkManager.pas',
  uMimicsNetwork in 'uMimicsNetwork.pas',
  uDataBuffer in '..\network\uDataBuffer.pas',
  uNetBaseSocket in '..\network\uNetBaseSocket.pas',
  uPacketRegister in '..\network\uPacketRegister.pas',
  uTCPClient in '..\network\uTCPClient.pas',
  uTCPDatatype in '..\network\uTCPDatatype.pas',
  uTCPServer in '..\network\uTCPServer.pas',
  uMimicsSystem in 'uMimicsSystem.pas',
  uThreadTimer in '..\framework\LibBaseUtils\Counter\uThreadTimer.pas',
  uVirtualTime in '..\framework\LibBaseUtils\Counter\uVirtualTime.pas',
  uBaseComponent in '..\components\uBaseComponent.pas',
  uIPMS_Data in '..\components\uIPMS_Data.pas',
  uSteppers in '..\framework\LibBaseUtils\Counter\uSteppers.pas',
  ufrmLogger in 'ufrmLogger.pas' {frmLogs},
  ufrmAlarmConfiguration in 'popmenu\ufrmAlarmConfiguration.pas' {frmAlarmConfiguration},
  ufrmAlarmString in 'popmenu\ufrmAlarmString.pas' {frmSelectAlarmString},
  ufrmAlarmStringIndex in 'popmenu\ufrmAlarmStringIndex.pas' {Form4},
  ufrmAttributeSet in 'popmenu\ufrmAttributeSet.pas' {frmNewAttribute},
  ufrmEdtAttribute in 'popmenu\ufrmEdtAttribute.pas' {frmEdtAttribute},
  ufrmEdtEnumeration in 'popmenu\ufrmEdtEnumeration.pas' {frmEdtEnumeration},
  ufrmEdtExpression in 'popmenu\ufrmEdtExpression.pas' {frmEditExpression},
  ufrmEdtMeasure in 'popmenu\ufrmEdtMeasure.pas' {frmEdtMeasure},
  ufrmHelp in 'popmenu\ufrmHelp.pas' {frmHelp},
  ufrmHistoricalRealtime in 'popmenu\ufrmHistoricalRealtime.pas' {frmHistoricalRealtime},
  ufrmLineDisplay in 'popmenu\ufrmLineDisplay.pas' {frmLineDisplay},
  ufrmLineMap in 'popmenu\ufrmLineMap.pas' {frmLineMap},
  ufrmNewAttribute in 'popmenu\ufrmNewAttribute.pas' {Form3},
  ufrmNewEnumeration in 'popmenu\ufrmNewEnumeration.pas' {frmNewEnumeration},
  ufrmNewMeasure in 'popmenu\ufrmNewMeasure.pas' {frmNewMeasure},
  ufrmNewPoint in 'popmenu\ufrmNewPoint.pas' {Form1},
  ufrmNewResource in 'popmenu\ufrmNewResource.pas' {frmNewResource},
  ufrmNewValue in 'popmenu\ufrmNewValue.pas' {frmNewValue},
  ufrmODBCAdmin in 'popmenu\ufrmODBCAdmin.pas' {frmODBCAdmin},
  ufrmPointPropts in 'popmenu\ufrmPointPropts.pas' {frmPointPropts},
  ufrmPointView in 'popmenu\ufrmPointView.pas' {frmPointView},
  ufrmProperties in 'popmenu\ufrmProperties.pas' {frmProperts},
  ufrmPropertiesContainer in 'popmenu\ufrmPropertiesContainer.pas' {frmContainer},
  ufrmPropertiesScreen in 'popmenu\ufrmPropertiesScreen.pas' {frmScreen},
  ufrmSelectAlarmClass in 'popmenu\ufrmSelectAlarmClass.pas' {frmSelectAlarmClass},
  ufrmSelectDevice in 'popmenu\ufrmSelectDevice.pas' {frmSelectDevice},
  ufrmSelectEnumeration in 'popmenu\ufrmSelectEnumeration.pas' {frmSelectEnumeration},
  ufrmSelectMeasure in 'popmenu\ufrmSelectMeasure.pas' {frmSelectMeasure},
  ufrmSelectPoint in 'popmenu\ufrmSelectPoint.pas' {Form2},
  ufrmSelectPointType in 'popmenu\ufrmSelectPointType.pas' {frmPointType},
  ufrmSelectResource in 'popmenu\ufrmSelectResource.pas' {frmSelectResource},
  ufrmValuePropts in 'popmenu\ufrmValuePropts.pas' {frmValuePropts},
  ufrmAlarmSummary in 'mimic\ufrmAlarmSummary.pas' {frmAlarmSummary},
  ufrmAlarmHistory in 'mimic\ufrmAlarmHistory.pas' {frmAlarmHistory},
  ufrmConfDateTime in 'popmenu\ufrmConfDateTime.pas' {frmConfDateTime},
  ufrmSelectSort in 'popmenu\ufrmSelectSort.pas' {frmSelectSort},
  ufrmEdtFilter in 'popmenu\ufrmEdtFilter.pas' {frmEdtFilter},
  ufrmSelectValue in 'popmenu\ufrmSelectValue.pas' {frmSelectValue},
  ufrmSelectFieldView in 'popmenu\ufrmSelectFieldView.pas' {frmSelectFieldView},
  ufrmAlarmPresentation in 'mimic\ufrmAlarmPresentation.pas' {frmAlarmPresentation},
  ufrmCAP in 'mimic\ufrmCAP.pas' {frmCAP},
  uAnalogSensor in '..\components\uAnalogSensor.pas',
  uCircuitBreakerElement in '..\components\uCircuitBreakerElement.pas',
  uValveProportionally in '..\components\uValveProportionally.pas',
  uControlElement in '..\components\uControlElement.pas',
  uMotorControlDoubleSpeed in '..\components\uMotorControlDoubleSpeed.pas',
  uMotorControlElement in '..\components\uMotorControlElement.pas',
  uMotorControlStandby in '..\components\uMotorControlStandby.pas',
  uRunningHour in '..\components\uRunningHour.pas',
  uSetpoint in '..\components\uSetpoint.pas',
  uSwitchElement in '..\components\uSwitchElement.pas',
  uSwitchEvent in '..\components\uSwitchEvent.pas',
  uSwitchNBCD in '..\components\uSwitchNBCD.pas',
  uSwitchTriangle in '..\components\uSwitchTriangle.pas',
  uTankSensor in '..\components\uTankSensor.pas',
  uValveControl in '..\components\uValveControl.pas',
  uHorizontalBar in '..\components\uHorizontalBar.pas',
  uVerticalBar in '..\components\uVerticalBar.pas',
  ufrmFuelOilSystem in 'mimic\ufrmFuelOilSystem.pas' {frmFuelOilSystem},
  ufrmAuthorization in 'popmenu\ufrmAuthorization.pas' {frmAuthorization},
  uComputer in '..\components\uComputer.pas',
  uShortcut in '..\components\uShortcut.pas',
  uDBSupportClasses in '..\common\uDBSupportClasses.pas',
  uFreezeFrom in '..\common\uFreezeFrom.pas' {frmFreeze},
  uElementTables in '..\elements\uElementTables.pas',
  ufrmSetpoint in 'popmenu\ufrmSetpoint.pas' {frmSetpoint},
  ufrmSelectElement in 'popmenu\ufrmSelectElement.pas' {frmSelectElement},
  ufrmAxis in '..\datatrend\ufrmAxis.pas' {frmAxis},
  ufrmChart in '..\datatrend\ufrmChart.pas' {frmChartOption},
  ufrmDataTrend in '..\datatrend\ufrmDataTrend.pas' {frmTrending},
  ufrmExpression in '..\datatrend\ufrmExpression.pas' {frmExpression},
  ufrmGridOption in '..\datatrend\ufrmGridOption.pas' {frmGrid},
  ufrmLegend in '..\datatrend\ufrmLegend.pas' {frmLegend},
  ufrmLineAttribute in '..\datatrend\ufrmLineAttribute.pas' {frmLineAttribute},
  ufrmLinePoint in '..\datatrend\ufrmLinePoint.pas' {frmPointID},
  ufrmLines in '..\datatrend\ufrmLines.pas' {frmLines},
  ufrmLogged in '..\datatrend\ufrmLogged.pas' {frmLogged},
  ufrmLoggedExpression in '..\datatrend\ufrmLoggedExpression.pas' {frmLoggedExpression},
  ufrmNewAxis in '..\datatrend\ufrmNewAxis.pas' {frmNewAxis},
  ufrmSetAxisProp in '..\datatrend\ufrmSetAxisProp.pas' {frmSetAxisProp},
  ufrmSetXAxisProp in '..\datatrend\ufrmSetXAxisProp.pas' {frmSetXAxisProp},
  ufrmSetYAxisProp in '..\datatrend\ufrmSetYAxisProp.pas' {frmSetYAxisProp},
  ufrmTableSelect in '..\datatrend\ufrmTableSelect.pas' {frmTableSelect},
  uAxisAttribute in '..\components\TrendChart\uAxisAttribute.pas',
  uGridAttribute in '..\components\TrendChart\uGridAttribute.pas',
  uLegendAttribute in '..\components\TrendChart\uLegendAttribute.pas',
  uLineAttribute in '..\components\TrendChart\uLineAttribute.pas',
  uTrendChart in '..\components\TrendChart\uTrendChart.pas',
  uTrendData in '..\components\TrendChart\uTrendData.pas',
  uTrendDataSeries in '..\components\TrendChart\uTrendDataSeries.pas',
  uTrendDataType in '..\components\TrendChart\uTrendDataType.pas',
  ufrmSelectTrend in '..\datatrend\ufrmSelectTrend.pas' {frmSelectTrend},
  ufrmTrendControlPropts in '..\datatrend\ufrmTrendControlPropts.pas' {frmTrenControlPropts},
  ufrmReport in 'popmenu\ufrmReport.pas' {frmReport},
  ufrmAlarmSummaryAUX in 'mimic\ufrmAlarmSummaryAUX.pas' {frmAlarmSummaryAUX},
  ufrmAlarmSummaryBALL in 'mimic\ufrmAlarmSummaryBALL.pas' {frmAlarmSummaryBALL},
  ufrmAlarmSummaryDG in 'mimic\ufrmAlarmSummaryDG.pas' {frmAlarmSummaryDG},
  ufrmAlarmSummaryDIST in 'mimic\ufrmAlarmSummaryDIST.pas' {frmAlarmSummaryDIST},
  ufrmAlarmSummaryDMST in 'mimic\ufrmAlarmSummaryDMST.pas' {frmAlarmSummaryDMST},
  ufrmAlarmSummaryFFDC in 'mimic\ufrmAlarmSummaryFFDC.pas' {frmAlarmSummaryFFDC},
  ufrmAlarmSummaryFUEL in 'mimic\ufrmAlarmSummaryFUEL.pas' {frmAlarmSummaryFUEL},
  ufrmAlarmSummaryHVAC in 'mimic\ufrmAlarmSummaryHVAC.pas' {frmAlarmSummaryHVAC},
  ufrmAlarmSummaryIPMS in 'mimic\ufrmAlarmSummaryIPMS.pas' {frmAlarmSummaryIPMS},
  ufrmAlarmSummaryNAV in 'mimic\ufrmAlarmSummaryNAV.pas' {frmAlarmSummaryNAV},
  ufrmAlarmSummaryPROP in 'mimic\ufrmAlarmSummaryPROP.pas' {frmAlarmSummaryPROP},
  lognya in '..\components\TrendChart\lognya.pas';

{$R *.res}
{$R IPMS_Resource.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;

  SysMimics := TMimicSystem.Create;

  Application.CreateForm(TfrmMainDisplay, frmMainDisplay);
  Application.CreateForm(TfrmLogin, frmLogin);
  Application.CreateForm(TfrmSetpoint, frmSetpoint);
  Application.CreateForm(TfrmSelectElement, frmSelectElement);
  Application.CreateForm(TfrmReport, frmReport);
  Application.CreateForm(TForm5, Form5);
  SysMimics.Mimic.SetForm(frmMainDisplay);
  SysMimics.Mimic.ShowMimic(mtLogin);

  SysMimics.Network.StartNetwork;

  Application.Run;
end.

