[Listen]
;archos bridge/archos connector
PortlistenConnector = 2222
;restart archos/ archos monitor
PortlistenControl  = 22222    
portlistenSessionVoip = 33033

[Server]
addrSessionVoip  = 127.0.0.1
portSessionVoip = 33033
addrConnector = 127.0.0.1
portConnector = 2222
addrControl = 127.0.0.1
portControl = 22222
addrServer = 192.168.1.134
portServer = 5001
addrBridge = 192.168.5.230
portBridge	  = 2120

[AutoStart]
WtPreplay = 30
WtRun = 30
EnableBridge = 0
EnableLinux = 1

[Putty]
Param = -ssh root@192.168.1.30 -pw koplop;

[Role]
Cubicle = 1
Console = CCTV2

[Port]
InternalSIPPort  = 6000
InternalVoipPort = 36000
ExternalSIPPort  = 7000
ExternalVoipPort = 37000

[Room]
External = 3050
Internal = 3100

[SkinPhone]
;1 = NFS, 2 IPMS, 3 IPMS800x600, 4 TCMS1440x900, 5 TCMS800x600, 6 INCS4X3Small,
;7 INCS4X5Vert641x1065, 8 INCS4X5Vert800x1280, 9 INCS4X5Vert641x1024; 
;10 INCS4X3Horz600x800, 11 INCS4X3Horz641x1024, 12 APVC, 13 TCMS_PKR;
;101 IPMS phone handle no UI, 102 IPMS CCTV
Skin = 102

[Position]
Monitor = 1
Top = 0
Left = 0

[Cub]
TotalCubicle = 1

[Start]
Auto = 1
Mode = 0

[App]
Tray 	= 0
Border 	= 1

[ArduinoBtn]
Name=COM69
Enable=0
BaudRate=13
DataBits=3
StopBits=0
ParityBits=0
FlowControl=2